ALTER TABLE public.beta_signups
  ALTER COLUMN name DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS source TEXT,
  ADD COLUMN IF NOT EXISTS roi_leads INTEGER,
  ADD COLUMN IF NOT EXISTS roi_commission INTEGER,
  ADD COLUMN IF NOT EXISTS roi_response_min INTEGER,
  ADD COLUMN IF NOT EXISTS roi_cold_pct INTEGER,
  ADD COLUMN IF NOT EXISTS roi_recovered_low INTEGER,
  ADD COLUMN IF NOT EXISTS roi_recovered_high INTEGER;